version: "3.9"
services:
  astdiskd:
    build: .
    command: bash -c "astctl static-disk add /robot/ & astdiskd"
    depends_on:
      - mosquitto
    volumes:
      - type: bind
        source: ./docker/usb/
        target: /robot/
  astprocd:
    build: .
    command: astprocd
    depends_on:
      - mosquitto
    volumes:
      - type: bind
        source: ./docker/usb/
        target: /robot/
  astmetad:
    build: .
    command: astmetad
    depends_on:
      - mosquitto
    volumes:
      - type: bind
        source: ./docker/usb/
        target: /robot/
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - type: bind
        source: ./docker/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
