from typing import Any

from dbus_next.constants import BusType

from .proxy_object import ProxyObject

class MessageBus:

    def __init__(self, *, bus_type: BusType = BusType.SESSION) -> None: ...
    async def connect(self) -> 'MessageBus': ...

    async def introspect(self, bus_name: str, path: str, timeout: float = 30.0) -> Any: ...
    def get_proxy_object(self, bus_name: str, path: str, introspection: Any) -> ProxyObject: ...
