from typing import Any, Callable

class ProxyInterface:
    
    def call_get_managed_objects(self) -> Any: ...
    def get_mount_points(self) -> Any: ...
    def on_interfaces_added(self, func: Callable[..., None]) -> None: ...
    async def get_id_uuid(self) -> str: ...

class ProxyObject:

    def get_interface(self, interface_path: str) -> ProxyInterface: ...