name: Build and Publish docs

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.12]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
      - name: Install GraphViz
        run: sudo apt install graphviz

      - name: Build newsletters
        run: make docs
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
